[package]
name = "wotw_seedgen_c_interop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wotw_seedgen = { git = "https://github.com/ori-community/wotw-seedgen.git", branch = "entrance_randomizer" }
cty = "0.2"
